ImageGallery/Models/ErrorViewModel.cs
namespace ImageGallery.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImageGallery/Models/GalleryViewModel.cs
using ImageGallery.Services.Constants;
using ImageGallery.Services.Responses;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace ImageGallery.Models
{
    public class GalleryViewModel
    {
        public Dictionary<string, int> UrlsAndVotes { get; set; } = new Dictionary<string, int>();

        public List<SelectListItem> Marks { get; set; }

        public int Count { get; set; }

        public int Current { get; set; }

        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, Constants.NUMBER_OF_PICTURES));

        public int VotesRemaining { get; set; }

        public GalleryViewModel(GalleryLoadResponse galleryLoadResponse)
        {
            Count = galleryLoadResponse.Count;
            UrlsAndVotes = galleryLoadResponse.ImageURLsAndVotes;
            Current = galleryLoadResponse.CurrentPage;
            VotesRemaining = galleryLoadResponse.VotesRemaining;

            Marks = new List<SelectListItem>
            {
                new SelectListItem { Value = "0", Text = "None"},
                new SelectListItem { Value = "1", Text = "1"},
                new SelectListItem { Value = "2", Text = "2"},
                new SelectListItem { Value = "3", Text = "3"},
                new SelectListItem { Value = "4", Text = "4"},
                new SelectListItem { Value = "5", Text = "5"},
                new SelectListItem { Value = "6", Text = "6"},
                new SelectListItem { Value = "7", Text = "7"},
                new SelectListItem { Value = "8", Text = "8"},
                new SelectListItem { Value = "9", Text = "9"},
                new SelectListItem { Value = "10", Text = "10"}
            };
        }
    }
}

ImageGallery/Models/ImageSummaryViewModel.cs
namespace ImageGallery.Models
{
    public class ImageSummaryViewModel
    {
        public int UserVote { get; set; }

        public int TotalVotes { get; set; }

        public string AverageVote { get; set; }
    }
}

ImageGallery/Models/SummaryViewModel.cs
using ImageGallery.Services.Responses;
using System.Collections.Generic;

namespace ImageGallery.Models
{
    public class SummaryViewModel
    {
        public Dictionary<string, ImageSummaryViewModel> ImageSummaries { get; set; } = new Dictionary<string, ImageSummaryViewModel>();
        public SummaryViewModel(SummaryResponse response)
        {
            foreach (var kvp in response.ImagesWithSummaries)
            {
                ImageSummaries.Add(
                    kvp.Key,
                    new ImageSummaryViewModel
                    {
                        AverageVote = kvp.Value.AverageVote.ToString("N2"),
                        TotalVotes = kvp.Value.TotalVotes,
                        UserVote = kvp.Value.UserVote
                    });
            }    
        }
    }
}

ImageGallery/Controllers/GalleryController.cs
using ImageGallery.Models;
using ImageGallery.Services.Requests;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ImageGallery.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IMediator _mediator;

        public GalleryController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [Route("Gallery/Index/{pageNumber?}")]
        public async Task<IActionResult> Index(int pageNumber)
        {
            var result = await _mediator.Send(new GalleryLoadRequest(pageNumber));

            if (result.VotingDone)
            {
                return RedirectToAction(nameof(Summary));
            }
            else if (result.HasErrors)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(new GalleryViewModel(result));
        }

        public async Task<IActionResult> Summary()
        {
            var result = await _mediator.Send(new SummaryRequest());

            if (result.HasErrors)
            {
                return RedirectToAction("Error", "Home");
            }
            else if (result.ShowSummary)
            {
                return View(new SummaryViewModel(result));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

ImageGallery/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ImageGallery.Models;

namespace ImageGallery.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ImageGallery/Controllers/VotesController.cs
using System.Threading.Tasks;
using ImageGallery.Services.Requests;
using ImageGallery.Shared.Extensions;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace ImageGallery.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class VotesController : ControllerBase
    {
        private readonly IMediator _mediator;

        public VotesController(IMediator mediator)
        {
            _mediator = mediator;
        }
        [HttpPut]
        public async Task<IActionResult> Add([FromBody]AddVoteRequest request)
        {
            var result = await _mediator.Send(request);
            if (result.HasErrors)
            {
                return BadRequest(new { Message = result.ErrorMessages.GetErrorMessagesFormated() });
            }

            return Ok(result);
        }
    }
}

ImageGallery/Views/Gallery/Index.cshtml
@model ImageGallery.Models.GalleryViewModel
@{
    ViewData["Title"] = "Voting";
}

<div class="container">

    <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Remaining votes - <span id="votesCounter">@Model.VotesRemaining</span></h1>

    <hr class="mt-2 mb-5">

    <div class="row text-center text-lg-left">
        @foreach (var imgUrl in Model.UrlsAndVotes)
        {
            <div class="col-lg-3 col-md-4 col-6 img-thumbnail">
                <div style="display:block">
                    <a href="@imgUrl.Key" target="_blank" class="d-block mb-4 h-100">
                        <img class="img-thumbnail" src="@imgUrl.Key" alt="" style="width: 100%; height: 100px; object-fit:cover">
                    </a>
                </div>
                <div>
                    <div style="float:left">Your vote: </div>
                    <select asp-items="Model.Marks" style="float:right" imageUrl="@imgUrl.Key" asp-for="@Model.UrlsAndVotes[imgUrl.Key]"></select>
                </div>
            </div>
        }
    </div>

</div>

<div>
    <ul class="pagination">
        @for (var i = 0; i < Model.TotalPages; i++)
        {
            <li class="page-item @(i == Model.Current ? "active" : "")">
                <a asp-area="" asp-controller="Gallery" asp-action="Index" asp-route-pageNumber="@i" class="page-link">@i</a>
            </li>
        }
    </ul>
</div>
@section scripts{
    <script src="~/js/dropdown.js"></script>
}
<!-- /.container -->

ImageGallery/Views/Gallery/Summary.cshtml
@model ImageGallery.Models.SummaryViewModel
@{
    ViewData["Title"] = "Summary";
}

<div class="container">

    <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Summary page - overview of images you voted on</h1>

    <hr class="mt-2 mb-5">

    <div class="row text-center text-lg-left">
        @foreach (var imgSummary in Model.ImageSummaries)
        {
            <div class="col-md-12 img-thumbnail">
                <div class="row text-center text-lg-left">
                    <div class="col-md-8">
                        <a href="@imgSummary.Key" target="_blank" class="d-block mb-4 h-100">
                            <img class="img-thumbnail" src="@imgSummary.Key" alt="" style="width: 100%; height: 300px; object-fit:cover">
                        </a>
                    </div>
                    <div class="col-md-4">
                        <div class="text-center">Your vote: @imgSummary.Value.UserVote</div>
                        <div class="text-center">Average vote: @imgSummary.Value.AverageVote</div>
                        <div class="text-center">Total votes: @imgSummary.Value.TotalVotes</div>
                    </div>
                </div>
            </div>
            <hr class="mt-2 mb-5">
        }
    </div>

</div>

ImageGallery/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to "Image Gallery"</h1>
    <p>You can start voting by clicking <a asp-area="" asp-controller="Gallery" asp-action="Index" asp-route-pageNumber="0">start voting</a> or by navigating to gallery in the nav bar.</p>
    <p>You can vote on 10 pictures in total. No less no more. You can also change your vote at any time. Bear in mind when you submit your last vote, you will be automatically redirected to the summary page</p>
</div>

ImageGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Image Gallery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Image Gallery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index" asp-route-pageNumber="0">Gallery</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="alert alert-danger" role="alert" id="errorDisplay" style="visibility:hidden">
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ImageGallery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>